// SPDX-FileCopyrightText: 2026 Igor Santos
// SPDX-License-Identifier: Apache-2.0

//! Effort-tier variants of an agent (`reviewer-low`, `reviewer-xhigh`),
//! rendered in memory and handed to Claude Code for one session with
//! `--agents`. No variant is a committed file: 11 agents times four other
//! tiers would add dozens of descriptions to every session's context, so
//! the launcher injects only the variants a session can use.
//!
//! The base `agents/<name>.md` is the single source. A variant keeps its
//! `tools`, `model` and body, and differs in `name`, a one-line `description`
//! and `effort`. The `Agent` tool has no per-call effort override, so a
//! distinct agent definition is the only way an orchestrator can pick an
//! effort per spawn (ADR-0017).

use crate::effort::rank;
use serde_json::{json, Map, Value};
use std::fs;
use std::path::Path;

/// First text of the header comment the retired generated files carried. The
/// agents check refuses any file that still has it.
pub const MARKER: &str = "<!-- GENERATED by `playbook agents gen`";

/// Every effort tier, lowest first, as Claude Code names them.
pub const TIERS: [&str; 5] = ["low", "medium", "high", "xhigh", "max"];

/// Every base agent with the tiers it can be rendered at. A tier equal to the
/// base file's own effort renders nothing. `playbook agents check` fails when
/// an agent file has no entry here.
pub const VARIANTS: [(&str, &[&str]); 11] = [
    ("analyst", &TIERS),
    ("auditor", &TIERS),
    ("cheap-checker", &TIERS),
    ("collector", &TIERS),
    ("critic", &TIERS),
    ("fact-checker", &TIERS),
    ("git", &TIERS),
    ("implementer", &TIERS),
    ("review-triage", &TIERS),
    ("reviewer", &TIERS),
    ("test-reviewer", &TIERS),
];

/// Agents whose work gets harder with the diff, so a session also gets the
/// `xhigh` variant. Every other agent only gets cheaper tiers. Haiku agents are
/// left out on purpose: the model cap (`src/effort/model_cap.rs`) stops them at
/// `medium`, so an `xhigh` variant would never be passed.
const ESCALATE: [&str; 3] = ["critic", "implementer", "reviewer"];

/// Haiku checking and classifying agents that ship at `low`. A session also
/// gets their `medium` tier for a harder diff, the highest Haiku tier the
/// model-aware cap allows (`src/effort/model_cap.rs`).
const ESCALATE_MEDIUM: [&str; 3] = ["cheap-checker", "review-triage", "test-reviewer"];

/// The largest `--agents` value the launcher will pass. Linux caps one
/// argument at 128 KiB, so stay under it.
const MAX_JSON_BYTES: usize = 120_000;

/// Which variants a session gets.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Cheaper tiers for every agent, plus `xhigh` for `ESCALATE` agents.
    Auto,
    /// Every tier except the base one, `max` included.
    All,
    /// None.
    Off,
}

impl Mode {
    pub fn parse(text: &str) -> Option<Mode> {
        match text {
            "auto" => Some(Mode::Auto),
            "all" => Some(Mode::All),
            "off" => Some(Mode::Off),
            _ => None,
        }
    }
}

/// The agent name of a variant.
pub fn variant_name(base: &str, tier: &str) -> String {
    format!("{base}-{tier}")
}

/// A base agent file split into what a variant reuses.
struct Base<'a> {
    tools: Vec<String>,
    model: Option<String>,
    effort: String,
    body: &'a str,
}

fn parse_base<'a>(base: &str, content: &'a str) -> Result<Base<'a>, String> {
    let mut lines = content.split_inclusive('\n');
    let first = lines.next().unwrap_or("");
    if first.trim_end() != "---" {
        return Err(format!("{base}: missing opening --- frontmatter delimiter"));
    }
    let (mut tools, mut model, mut effort) = (Vec::new(), None, None);
    let mut consumed = first.len();
    let mut closed = false;
    for line in lines {
        consumed += line.len();
        let trimmed = line.trim_end();
        if trimmed == "---" {
            closed = true;
            break;
        }
        if let Some(v) = trimmed.strip_prefix("tools:") {
            tools = v
                .split(',')
                .map(|t| t.trim().to_string())
                .filter(|t| !t.is_empty())
                .collect();
        } else if let Some(v) = trimmed.strip_prefix("model:") {
            model = Some(v.trim().to_string());
        } else if let Some(v) = trimmed.strip_prefix("effort:") {
            effort = Some(v.trim().to_string());
        }
    }
    if !closed {
        return Err(format!("{base}: missing closing --- frontmatter delimiter"));
    }
    let effort = effort.ok_or_else(|| format!("{base}: needs an effort in its frontmatter"))?;
    Ok(Base {
        tools,
        model,
        effort,
        body: content.get(consumed..).unwrap_or(""),
    })
}

/// The definition of `base` at `tier` as an `--agents` entry, or `None` when
/// `tier` equals the base file's own effort.
pub fn render_definition(base: &str, content: &str, tier: &str) -> Result<Option<Value>, String> {
    if !TIERS.contains(&tier) {
        return Err(format!("{base}: unknown tier '{tier}'"));
    }
    let parsed = parse_base(base, content)?;
    if parsed.effort == tier {
        return Ok(None);
    }
    let mut def = Map::new();
    def.insert(
        "description".into(),
        json!(format!("{base} at {tier} effort. Same job and rules, chosen by diff size or an effort ceiling.")),
    );
    def.insert("prompt".into(), json!(parsed.body.trim_start_matches('\n')));
    if !parsed.tools.is_empty() {
        def.insert("tools".into(), json!(parsed.tools));
    }
    if let Some(model) = parsed.model {
        def.insert("model".into(), json!(model));
    }
    def.insert("effort".into(), json!(tier));
    Ok(Some(Value::Object(def)))
}

/// The tiers a session gets for one agent. `base_effort` is the file's own
/// effort and `ceiling` the lowest ceiling in play. Never above the ceiling,
/// never the base tier itself.
fn session_tiers(
    base: &str,
    base_effort: &str,
    ceiling: Option<&str>,
    mode: Mode,
) -> Vec<&'static str> {
    let (Some(base_rank), true) = (rank(base_effort), mode != Mode::Off) else {
        return Vec::new();
    };
    let limit = ceiling.and_then(rank);
    TIERS
        .iter()
        .copied()
        .filter(|t| {
            let r = rank(t).unwrap_or(usize::MAX);
            let within = limit.is_none_or(|l| r <= l);
            let wanted = match mode {
                Mode::All => true,
                Mode::Auto => {
                    r < base_rank
                        || (*t == "xhigh" && ESCALATE.contains(&base))
                        || (*t == "medium" && ESCALATE_MEDIUM.contains(&base))
                        || crate::effort::model_cap::opt_in(base).is_some_and(|(l, _)| l == *t)
                }
                Mode::Off => false,
            };
            within && wanted && r != base_rank
        })
        .collect()
}

/// The `--agents` entries for one session: every base agent under
/// `agents_dir` with its tiers from `session_tiers`. `ceiling_of` gives an
/// agent's lowest ceiling. A base file that cannot be read or rendered is
/// skipped. The result maps variant name to definition.
pub fn session_agents(
    agents_dir: &Path,
    mode: Mode,
    ceiling_of: &dyn Fn(&str) -> Option<String>,
) -> Map<String, Value> {
    let mut out = Map::new();
    for (base, _) in VARIANTS {
        let Ok(content) = fs::read_to_string(agents_dir.join(format!("{base}.md"))) else {
            continue;
        };
        let Ok(parsed) = parse_base(base, &content) else {
            continue;
        };
        let ceiling = crate::effort::lower(
            ceiling_of(base).as_deref(),
            crate::effort::model_cap::cap_for(parsed.model.as_deref(), base),
        )
        .map(str::to_string);
        for tier in session_tiers(base, &parsed.effort, ceiling.as_deref(), mode) {
            if let Ok(Some(def)) = render_definition(base, &content, tier) {
                out.insert(variant_name(base, tier), def);
            }
        }
    }
    out
}

/// `session_agents` serialized for `--agents`, trimmed to fit
/// `MAX_JSON_BYTES`: when too large it first drops the `xhigh` and `max`
/// variants, then gives up and returns nothing. Returns the JSON and the
/// variant names it holds.
pub fn session_json(
    agents_dir: &Path,
    mode: Mode,
    ceiling_of: &dyn Fn(&str) -> Option<String>,
) -> Option<(String, Vec<String>)> {
    let mut map = session_agents(agents_dir, mode, ceiling_of);
    let mut text = serde_json::to_string(&map).ok()?;
    if text.len() > MAX_JSON_BYTES {
        map.retain(|_, def| !matches!(def["effort"].as_str(), Some("xhigh" | "max")));
        text = serde_json::to_string(&map).ok()?;
    }
    if map.is_empty() || text.len() > MAX_JSON_BYTES {
        return None;
    }
    Some((text, map.keys().cloned().collect()))
}

#[cfg(test)]
mod tests {
    use super::*;

    const BASE: &str = "---\nname: sample\ndescription: \"A structurally read-only fixture.\"\ntools: Read, Grep\nmodel: sonnet\neffort: high\n---\n\nBody line.\n";

    #[test]
    fn a_definition_keeps_tools_model_and_body_and_changes_effort() {
        let def = render_definition("sample", BASE, "low").unwrap().unwrap();
        assert_eq!(def["effort"], "low");
        assert_eq!(def["model"], "sonnet");
        assert_eq!(def["tools"], json!(["Read", "Grep"]));
        assert_eq!(def["prompt"], "Body line.\n");
        let description = def["description"].as_str().unwrap();
        assert!(
            description.starts_with("sample at low effort."),
            "{description}"
        );
        assert!(description.len() < 120);
    }

    #[test]
    fn the_base_tier_renders_nothing() {
        assert_eq!(render_definition("sample", BASE, "high").unwrap(), None);
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(
            render_definition("sample", BASE, "xhigh"),
            render_definition("sample", BASE, "xhigh")
        );
    }

    #[test]
    fn unusable_bases_and_tiers_are_rejected_with_a_message() {
        let err = |text: &str, tier: &str| render_definition("sample", text, tier).unwrap_err();
        assert!(err("no frontmatter", "low").contains("missing opening ---"));
        assert!(err("---\nname: sample\n", "low").contains("missing closing ---"));
        let no_effort = BASE.replace("effort: high\n", "");
        assert!(err(&no_effort, "low").contains("needs an effort"));
        assert!(err(BASE, "extreme").contains("unknown tier"));
    }

    #[test]
    fn auto_gives_cheaper_tiers_and_xhigh_only_to_escalating_agents() {
        assert_eq!(
            session_tiers("reviewer", "high", None, Mode::Auto),
            vec!["low", "medium", "xhigh"]
        );
        assert_eq!(
            session_tiers("test-reviewer", "high", None, Mode::Auto),
            vec!["low", "medium"]
        );
        // A Haiku checker that ships at low also gets medium for a harder diff.
        assert_eq!(
            session_tiers("test-reviewer", "low", None, Mode::Auto),
            vec!["medium"]
        );
        assert_eq!(
            session_tiers("cheap-checker", "low", None, Mode::Auto),
            vec!["medium"]
        );
        assert!(session_tiers("collector", "low", None, Mode::Auto).is_empty());
        // `git` opted in to xhigh for drafting (src/effort/model_cap.rs).
        assert_eq!(session_tiers("git", "low", None, Mode::Auto), vec!["xhigh"]);
    }

    #[test]
    fn a_ceiling_cuts_the_tiers_above_it() {
        assert_eq!(
            session_tiers("reviewer", "high", Some("medium"), Mode::Auto),
            vec!["low", "medium"]
        );
        assert_eq!(
            session_tiers("reviewer", "high", Some("low"), Mode::All),
            vec!["low"]
        );
    }

    #[test]
    fn all_adds_max_and_off_adds_nothing() {
        assert_eq!(
            session_tiers("git", "low", None, Mode::All),
            vec!["medium", "high", "xhigh", "max"]
        );
        assert!(session_tiers("reviewer", "high", None, Mode::Off).is_empty());
    }

    #[test]
    fn every_base_agent_lists_every_tier() {
        for (base, tiers) in VARIANTS {
            assert_eq!(tiers, &TIERS, "{base}");
        }
        for name in ESCALATE {
            assert!(VARIANTS.iter().any(|(b, _)| *b == name), "{name}");
        }
    }

    #[test]
    fn a_session_json_names_its_variants_and_stays_under_the_cap() {
        let dir = std::env::temp_dir().join(format!("pb-variants-{}", crate::testing::run_id()));
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("reviewer.md"), BASE).unwrap();
        let (text, names) = session_json(&dir, Mode::Auto, &|_| None).unwrap();
        assert!(text.len() < MAX_JSON_BYTES);
        assert_eq!(
            names,
            vec!["reviewer-low", "reviewer-medium", "reviewer-xhigh"]
        );
        assert!(session_json(&dir, Mode::Off, &|_| None).is_none());
    }

    #[test]
    fn a_haiku_agent_never_gets_a_max_variant_even_in_all_mode() {
        let content =
            "---\nname: c\ndescription: d\ntools: Read\nmodel: haiku\neffort: low\n---\nBody\n";
        let dir =
            std::env::temp_dir().join(format!("pb-variants-haiku-{}", crate::testing::run_id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("cheap-checker.md"), content).unwrap();
        let map = session_agents(&dir, Mode::All, &|_| None);
        let efforts: Vec<&str> = map.values().filter_map(|d| d["effort"].as_str()).collect();
        assert!(!efforts.contains(&"max"), "{efforts:?}");
        assert!(!efforts.contains(&"xhigh"), "{efforts:?}");
        assert!(efforts.contains(&"medium"), "{efforts:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn the_git_agent_gets_its_xhigh_variant_in_auto_mode() {
        let content =
            "---\nname: g\ndescription: d\ntools: Bash\nmodel: haiku\neffort: low\n---\nBody\n";
        let dir =
            std::env::temp_dir().join(format!("pb-variants-git-{}", crate::testing::run_id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("git.md"), content).unwrap();
        let map = session_agents(&dir, Mode::Auto, &|_| None);
        assert!(map.contains_key("git-xhigh"), "{:?}", map.keys());
        assert!(!map.contains_key("git-max"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn the_shipped_auto_set_has_a_medium_tier_for_haiku_checkers_and_no_haiku_xhigh() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("agents");
        let set = session_agents(&dir, Mode::Auto, &|_| None);
        for name in [
            "cheap-checker-medium",
            "review-triage-medium",
            "test-reviewer-medium",
        ] {
            assert!(
                set.contains_key(name),
                "{name} is missing from the auto set"
            );
        }
        for (name, def) in &set {
            let effort = def["effort"].as_str().unwrap_or("");
            let haiku = def["model"].as_str().is_some_and(|m| m.contains("haiku"));
            assert!(
                !(haiku && effort == "max"),
                "{name}: no Haiku variant may run at max"
            );
        }
        // What the model sees of the set in its agent list stays small.
        let listed: usize = set
            .iter()
            .map(|(k, v)| k.len() + v["description"].as_str().map_or(0, str::len))
            .sum();
        assert!(
            listed < 3_000,
            "the variant list costs {listed} bytes of context"
        );
    }
}
