// SPDX-FileCopyrightText: 2026 Igor Santos
// SPDX-License-Identifier: Apache-2.0

//! Generates the effort-tier variants of an agent (`reviewer-low`,
//! `reviewer-xhigh`). The base `agents/<name>.md` is the single source: a
//! variant differs only in `name`, the `description` prefix and `effort`.
//! The `Agent` tool has no per-call effort override, so a distinct agent
//! file is the only way an orchestrator can pick an effort per spawn.

use std::fs;
use std::path::Path;

/// First text of the header comment every generated variant carries.
pub const MARKER: &str = "<!-- GENERATED by `playbook agents gen`";

/// Which agents get which tier variants. Edit this table, then run
/// `playbook agents gen`. A tier equal to the base effort is rejected.
pub const VARIANTS: [(&str, &[&str]); 5] = [
    ("analyst", &["low", "xhigh"]),
    ("critic", &["low", "xhigh"]),
    ("fact-checker", &["xhigh"]),
    ("implementer", &["low", "xhigh"]),
    ("reviewer", &["low", "xhigh"]),
];

/// The agent name of a variant, which is also its file stem.
pub fn variant_name(base: &str, tier: &str) -> String {
    format!("{base}-{tier}")
}

fn capitalize(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// The variant text for `tier`, derived from the base file's `content`.
pub fn render_variant(base: &str, content: &str, tier: &str) -> Result<String, String> {
    let mut lines: Vec<String> = content.split('\n').map(str::to_string).collect();
    if lines.first().map(String::as_str) != Some("---") {
        return Err(format!("{base}: missing opening --- frontmatter delimiter"));
    }
    let close = lines
        .iter()
        .skip(1)
        .position(|l| l == "---")
        .map(|i| i + 1)
        .ok_or_else(|| format!("{base}: missing closing --- frontmatter delimiter"))?;

    let prefix = format!("{}-effort variant of {base}. ", capitalize(tier));
    let (mut named, mut described, mut efforted) = (false, false, false);
    for line in lines.iter_mut().take(close).skip(1) {
        if line.starts_with("name:") {
            *line = format!("name: {}", variant_name(base, tier));
            named = true;
        } else if line.starts_with("effort:") {
            if line["effort:".len()..].trim() == tier {
                return Err(format!("{base}: base effort is already '{tier}'"));
            }
            *line = format!("effort: {tier}");
            efforted = true;
        } else if let Some(rest) = line.strip_prefix("description:") {
            let value = rest.trim();
            *line = match value.chars().next() {
                Some(q @ ('"' | '\'')) => format!("description: {q}{prefix}{}", &value[1..]),
                _ => format!("description: {prefix}{value}"),
            };
            described = true;
        }
    }
    if !(named && described && efforted) {
        return Err(format!(
            "{base}: needs name, description and effort in its frontmatter"
        ));
    }

    let header = format!(
        "{MARKER} from agents/{base}.md. Do not edit: change the base file and rerun it. -->"
    );
    lines.insert(close + 1, header);
    Ok(lines.join("\n"))
}

/// Writes every variant next to its base (skipping a base absent from the dir), touching only files whose
/// content would change, and reports what it did.
pub fn generate(agents_dir: &Path) -> Result<String, String> {
    let (mut written, mut unchanged) = (0usize, 0usize);
    for (base, tiers) in VARIANTS {
        let base_path = agents_dir.join(format!("{base}.md"));
        let Ok(content) = fs::read_to_string(&base_path) else {
            continue;
        };
        for tier in tiers {
            let text = render_variant(base, &content, tier)?;
            let path = agents_dir.join(format!("{}.md", variant_name(base, tier)));
            if fs::read_to_string(&path).is_ok_and(|old| old == text) {
                unchanged += 1;
                continue;
            }
            fs::write(&path, text).map_err(|e| format!("cannot write {}: {e}", path.display()))?;
            written += 1;
        }
    }
    Ok(format!(
        "gen-agents: {written} variant(s) written, {unchanged} already current"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    const BASE: &str = "---\nname: sample\ndescription: \"A structurally read-only fixture.\"\ntools: Read\nmodel: sonnet\neffort: high\n---\n\nBody.\n";

    #[test]
    fn variant_changes_only_name_description_effort_and_adds_a_header() {
        let base = BASE.replace("Body.\n", "name: body\neffort: high\nBody.\n");
        let out = render_variant("sample", &base, "low").unwrap();
        let expected = format!(
            "---\nname: sample-low\ndescription: \"Low-effort variant of sample. A structurally read-only fixture.\"\ntools: Read\nmodel: sonnet\neffort: low\n---\n{MARKER} from agents/sample.md. Do not edit: change the base file and rerun it. -->\n\nname: body\neffort: high\nBody.\n"
        );
        assert_eq!(out, expected);
    }

    #[test]
    fn unquoted_and_single_quoted_descriptions_are_prefixed_in_place() {
        let plain = BASE.replace("\"A structurally read-only fixture.\"", "Plain text.");
        let out = render_variant("sample", &plain, "xhigh").unwrap();
        assert!(out.contains("description: Xhigh-effort variant of sample. Plain text.\n"));

        let single = BASE.replace("\"A structurally read-only fixture.\"", "'Quoted: text.'");
        let out = render_variant("sample", &single, "low").unwrap();
        assert!(out.contains("description: 'Low-effort variant of sample. Quoted: text.'\n"));
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(
            render_variant("sample", BASE, "low"),
            render_variant("sample", BASE, "low")
        );
    }

    #[test]
    fn rendering_rejects_unusable_bases_with_a_specific_message() {
        let err = |text: &str, tier: &str| render_variant("sample", text, tier).unwrap_err();
        assert!(err(BASE, "high").contains("base effort is already 'high'"));
        assert!(err("no frontmatter", "low").contains("missing opening ---"));
        assert!(err("---\nname: sample\n", "low").contains("missing closing ---"));
        let no_effort = BASE.replace("effort: high\n", "");
        assert!(err(&no_effort, "low").contains("needs name, description and effort"));
    }
}
