// SPDX-FileCopyrightText: 2026 Igor Santos
// SPDX-License-Identifier: Apache-2.0

//! `playbook shell-init`: the shell functions `pb`, `pbd`, `cc` and `ccd`,
//! printed for the rc file to `eval`. `pb` and `pbd` exist because `cc` is the
//! C compiler on most systems.
//!
//! The launcher itself is `playbook cc launch`. A child process cannot change
//! its parent's directory, so the function hands the binary a temp file in
//! `$PLAYBOOK_CC_CD_FILE`; when the launcher enters a worktree it writes the
//! path there, and the function `cd`s to it after the session. One line, no
//! stdout parsing, and the session keeps the terminal.

use super::shim::ShellKind;

/// The function bodies are valid in bash and zsh alike, so the one text is
/// shared; only the header names the shell it was generated for.
pub fn script(shell: ShellKind, define_cc: bool) -> String {
    let name = match shell {
        ShellKind::Bash => "bash",
        ShellKind::Zsh => "zsh",
    };
    let cc_aliases = if define_cc {
        "cc() { _playbook_cc -- \"$@\"; }\nccd() { _playbook_cc --skip-permissions -- \"$@\"; }\n"
    } else {
        ""
    };
    format!(
        r#"# playbook launcher for {name}, generated by `playbook shell-init`
_playbook_cc() {{
  local _pb_cd _pb_dir _pb_rc
  _pb_cd="$(mktemp "${{TMPDIR:-/tmp}}/playbook-cc.XXXXXX" 2>/dev/null)" || _pb_cd=""
  PLAYBOOK_CC_CD_FILE="$_pb_cd" command playbook cc launch "$@"
  _pb_rc=$?
  if [ -n "$_pb_cd" ]; then
    if [ -s "$_pb_cd" ]; then
      IFS= read -r _pb_dir < "$_pb_cd" && [ -d "$_pb_dir" ] && cd "$_pb_dir"
    fi
    rm -f "$_pb_cd"
  fi
  return $_pb_rc
}}
pb() {{ _playbook_cc -- "$@"; }}
pbd() {{ _playbook_cc --skip-permissions -- "$@"; }}
{cc_aliases}"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn both_shells_define_pb_pbd_cc_and_ccd() {
        for kind in [ShellKind::Bash, ShellKind::Zsh] {
            let text = script(kind, true);
            for name in ["pb", "pbd", "cc", "ccd"] {
                assert!(text.contains(&format!("\n{name}() {{")), "{name}");
            }
        }
    }

    #[test]
    fn no_cc_leaves_the_c_compiler_names_alone() {
        let text = script(ShellKind::Zsh, false);
        assert!(text.contains("\npb() {") && text.contains("\npbd() {"));
        assert!(!text.contains("\ncc() {") && !text.contains("\nccd() {"));
    }
}
