// SPDX-FileCopyrightText: 2026 Igor Santos
// SPDX-License-Identifier: Apache-2.0

//! `playbook shell-init`: the shell functions `ccc` and `ccd`, printed for the
//! rc file to `eval`. The launcher is `ccc`, not `cc`, because `cc` is the C
//! compiler on most systems.
//!
//! The launcher itself is `playbook cc launch`. A child process cannot change
//! its parent's directory, so the function hands the binary a temp file in
//! `$PLAYBOOK_CC_CD_FILE`; when the launcher enters a worktree it writes the
//! path there, and the function `cd`s to it after the session. One line, no
//! stdout parsing, and the session keeps the terminal.

use super::shim::ShellKind;

/// The function bodies are valid in bash and zsh alike, so the one text is
/// shared; only the header names the shell it was generated for.
pub fn script(shell: ShellKind) -> String {
    let name = match shell {
        ShellKind::Bash => "bash",
        ShellKind::Zsh => "zsh",
    };
    format!(
        r#"# playbook launcher for {name}, generated by `playbook shell-init`
_playbook_cc() {{
  local _pb_cd _pb_dir _pb_rc
  _pb_cd="$(mktemp "${{TMPDIR:-/tmp}}/playbook-cc.XXXXXX" 2>/dev/null)" || _pb_cd=""
  PLAYBOOK_CC_CD_FILE="$_pb_cd" command playbook cc launch "$@"
  _pb_rc=$?
  if [ -n "$_pb_cd" ]; then
    if [ -s "$_pb_cd" ]; then
      IFS= read -r _pb_dir < "$_pb_cd" && [ -d "$_pb_dir" ] && cd "$_pb_dir"
    fi
    rm -f "$_pb_cd"
  fi
  return $_pb_rc
}}
ccc() {{ _playbook_cc -- "$@"; }}
ccd() {{ _playbook_cc --skip-permissions -- "$@"; }}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn both_shells_define_ccc_and_ccd_and_never_cc() {
        for kind in [ShellKind::Bash, ShellKind::Zsh] {
            let text = script(kind);
            assert!(text.contains("\nccc() {"));
            assert!(text.contains("\nccd() {"));
            assert!(!text.contains("\ncc() {"));
            assert!(!text.contains("\npb() {") && !text.contains("\npbd() {"));
        }
    }
}
