// SPDX-FileCopyrightText: 2026 Igor Santos
// SPDX-License-Identifier: MIT

//! Finds and removes AI attribution in commit-style messages and in PR text.
//!
//! A message is a header, a body and trailers, and none of them may name
//! Claude or another AI agent. [`sanitize`] drops each line carrying an
//! attribution shape and reports only the line number and the shape's name.
//! The text of a removed line is never returned, because it can hold a
//! person's address or a session link.
//!
//! Only the shapes of attribution are matched, not every mention of a
//! product: prose such as "the Claude Code plugin" stays, while a
//! `Claude-Session:` line, a claude.ai link, a session id, a "Generated with"
//! footer or a credit trailer for an AI goes. A credit is an AI's when its
//! display name is an AI product or its address is a vendor or bot no-reply
//! address, so `Claude Dupont` or `jane@anthropic.com` stay. A `Signed-off-by`
//! is a person's certification, so only such an address makes it an AI's, never
//! the display name alone. Other trailers,
//! such as `Fixes` or `Reviewed-by` from a person, are never touched.

use std::ops::Range;

/// The kind of attribution a removed line carried.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Shape {
    /// A `Claude-Session:` line.
    SessionTrailer,
    /// A link to claude.ai.
    ClaudeLink,
    /// An agent session id such as `session_01AbC...`.
    SessionId,
    /// A tool footer such as "Generated with Claude Code".
    Footer,
    /// A `Co-authored-by`, `*-by` or `*-with` trailer crediting an AI.
    CreditTrailer,
    /// A trailer in the final trailer block whose token or value names an AI.
    AiTrailer,
    /// A line carrying the robot emoji.
    RobotEmoji,
}

impl Shape {
    /// A short label safe to print: it never contains the line's own text.
    pub fn name(self) -> &'static str {
        match self {
            Shape::SessionTrailer => "Claude-Session line",
            Shape::ClaudeLink => "claude.ai link",
            Shape::SessionId => "session id",
            Shape::Footer => "generated-with footer",
            Shape::CreditTrailer => "credit trailer naming an AI",
            Shape::AiTrailer => "trailer naming an AI",
            Shape::RobotEmoji => "robot emoji line",
        }
    }
}

/// A message with its attribution lines removed.
#[derive(Debug, PartialEq, Eq)]
pub struct Sanitized {
    pub text: String,
    /// `(line number from 1 in the input, shape)` for each removed line.
    pub removed: Vec<(usize, Shape)>,
}

impl Sanitized {
    /// One plain sentence per removed line: its number and shape, never its
    /// value.
    pub fn problems(&self) -> Vec<String> {
        self.removed
            .iter()
            .map(|(n, shape)| format!("line {n} carries AI attribution ({})", shape.name()))
            .collect()
    }
}

/// The line git prints above the diff that `git commit -v` appends.
const SCISSORS: &str = "# ------------------------ >8 ------------------------";

/// Prefixes git itself writes, which make a final paragraph a trailer block
/// even when most of its lines are prose.
const GIT_GENERATED_PREFIXES: [&str; 2] = ["Signed-off-by: ", "(cherry picked from commit "];

/// Names of AI tools and vendors, lowercase. A name matches as a whole word,
/// except `gpt-`, which is a prefix of model names such as `gpt-4o`. `devin`
/// is a common first name, so it is matched separately, by vendor address or
/// bot handle.
const AI_NAMES: [&str; 12] = [
    "claude",
    "anthropic",
    "openai",
    "chatgpt",
    "gpt-",
    "copilot",
    "gemini",
    "cursor",
    "codeium",
    "windsurf",
    "aider",
    "codex",
];

/// Openers of a tool footer such as "Generated with Claude Code".
const FOOTER_PHRASES: [&str; 9] = [
    "generated with",
    "generated by",
    "created with",
    "created by",
    "made with",
    "written by",
    "assisted by",
    "authored by",
    "built with",
];

const SESSION_ID_MIN_LEN: usize = 16;

/// Mail domains of the AI vendors.
const AI_EMAIL_DOMAINS: [&str; 9] = [
    "anthropic.com",
    "claude.ai",
    "openai.com",
    "cursor.com",
    "codeium.com",
    "windsurf.com",
    "devin.ai",
    "cognition.ai",
    "aider.chat",
];

/// Local parts of the addresses a vendor's tools send from.
const VENDOR_LOCAL_PARTS: [&str; 5] = [
    "noreply",
    "no-reply",
    "donotreply",
    "do-not-reply",
    "cursoragent",
];

/// Words a display name opens with when it is an AI product: `Claude Code`,
/// `GitHub Copilot`, `gpt-4o`. `devin` is a common first name, so it counts
/// only as `Devin AI`.
const PRODUCT_WORDS: [&str; 12] = [
    "claude",
    "anthropic",
    "openai",
    "chatgpt",
    "gpt",
    "copilot",
    "gemini",
    "cursor",
    "codeium",
    "windsurf",
    "aider",
    "codex",
];

/// Words that may follow a product word in a display name, besides version
/// numbers: `Claude Opus 4.5`, `Gemini 2.5 Pro`, `copilot-swe-agent[bot]`.
const NAME_QUALIFIERS: [&str; 24] = [
    "code",
    "opus",
    "sonnet",
    "haiku",
    "ai",
    "agent",
    "cli",
    "bot",
    "assistant",
    "swe",
    "integration",
    "pro",
    "flash",
    "mini",
    "nano",
    "lite",
    "ultra",
    "max",
    "plus",
    "turbo",
    "thinking",
    "preview",
    "instant",
    "reasoning",
];

/// Whole names an AI tool uses as a git identity.
const AI_IDENTITY_NAMES: [&str; 10] = [
    "claude",
    "claude code",
    "chatgpt",
    "github copilot",
    "copilot",
    "gemini",
    "cursor agent",
    "codex",
    "aider",
    "windsurf",
];

/// Removes every attribution line from a commit-style message, applying git's
/// trailer-block rule to the final paragraph.
pub fn sanitize(message: &str) -> Sanitized {
    scan(message, true)
}

/// Removes every attribution line from free text such as a PR title or body,
/// which has no trailer block.
pub fn sanitize_prose(text: &str) -> Sanitized {
    scan(text, false)
}

/// Like [`sanitize`], for the file an editor session leaves behind: the
/// template git appends (the scissors line and the diff below it, or a
/// trailing block of `#` lines) is kept byte for byte and never inspected,
/// since git removes it itself.
pub fn sanitize_editor(raw: &str) -> Sanitized {
    let (message, template) = split_template(raw);
    let mut sanitized = sanitize(message);
    sanitized.text.push_str(template);
    sanitized
}

/// Whether `message` has a `Signed-off-by:` line, which this repo's DCO check
/// requires on every commit.
pub fn has_sign_off(message: &str) -> bool {
    message.lines().any(|l| l.starts_with("Signed-off-by:"))
}

/// The lines [`sanitize`] would remove from `message`.
pub fn problems(message: &str) -> Vec<(usize, Shape)> {
    sanitize(message).removed
}

/// The lines [`sanitize_prose`] would remove from `text`.
pub fn prose_problems(text: &str) -> Vec<(usize, Shape)> {
    sanitize_prose(text).removed
}

fn scan(text: &str, trailer_rule: bool) -> Sanitized {
    let lines: Vec<&str> = text
        .split_inclusive('\n')
        .map(|line| line.trim_end_matches(['\n', '\r']))
        .collect();
    let block = if trailer_rule {
        trailer_block(&lines)
    } else {
        None
    };
    let removed = removed_lines(&lines, block.as_ref());
    Sanitized {
        text: drop_lines(text, &removed),
        removed,
    }
}

/// `text` without the lines `removed` names, and without the blank lines the
/// removal would leave stacked or at either end. Text with nothing removed
/// comes back unchanged.
pub fn drop_lines(text: &str, removed: &[(usize, Shape)]) -> String {
    if removed.is_empty() {
        return text.to_string();
    }
    let mut kept: Vec<&str> = Vec::new();
    let mut dropped_since_kept = false;
    for (i, line) in text.split_inclusive('\n').enumerate() {
        if removed.iter().any(|(n, _)| *n == i + 1) {
            dropped_since_kept = true;
            continue;
        }
        let blank = line.trim().is_empty();
        let after_blank = kept.last().is_none_or(|last| last.trim().is_empty());
        if blank && dropped_since_kept && after_blank {
            continue;
        }
        dropped_since_kept = dropped_since_kept && blank;
        kept.push(line);
    }
    tidy(kept, text.ends_with('\n'))
}

/// The attribution lines of `lines`. A trailer folded over indented
/// continuation lines is judged as one unit, and removed as one.
fn removed_lines(lines: &[&str], block: Option<&Range<usize>>) -> Vec<(usize, Shape)> {
    let mut removed = Vec::new();
    let mut covered_until = 0;
    for (i, line) in lines.iter().enumerate() {
        if i < covered_until {
            continue;
        }
        let in_block = block.is_some_and(|b| b.contains(&i));
        let end = folded_end(lines, i, in_block);
        if end == i + 1 {
            removed.extend(classify(line, in_block).map(|shape| (i + 1, shape)));
        } else {
            let unit = lines[i..end].iter().map(|l| l.trim()).collect::<Vec<_>>();
            if let Some(shape) = classify(&unit.join(" "), in_block) {
                removed.extend((i..end).map(|n| (n + 1, shape)));
                covered_until = end;
            }
        }
    }
    removed
}

/// The line after the last continuation of the trailer that starts at
/// `start`, or `start + 1` when it has none or is not a trailer. Only a trailer
/// in the final block folds: git reads an indented line anywhere else as text.
fn folded_end(lines: &[&str], start: usize, in_block: bool) -> usize {
    if !in_block || strict_trailer(lines[start]).is_none() {
        return start + 1;
    }
    let continuations = lines[start + 1..]
        .iter()
        .take_while(|l| l.starts_with(char::is_whitespace) && !l.trim().is_empty())
        .count();
    start + 1 + continuations
}

/// Joins the kept lines without the blank lines a removal leaves at either
/// end, ending with a newline only when the input did.
fn tidy(mut kept: Vec<&str>, ends_with_newline: bool) -> String {
    while kept.last().is_some_and(|l| l.trim().is_empty()) {
        kept.pop();
    }
    let start = kept
        .iter()
        .position(|l| !l.trim().is_empty())
        .unwrap_or(kept.len());
    let mut text: String = kept[start..].concat();
    if !text.is_empty() && ends_with_newline && !text.ends_with('\n') {
        text.push('\n');
    }
    if !ends_with_newline {
        text.truncate(text.trim_end_matches(['\n', '\r']).len());
    }
    text
}

/// Splits an editor file into the message and the template git appended: from
/// the scissors line down, or the trailing run of `#` lines with the blank
/// lines before it.
fn split_template(raw: &str) -> (&str, &str) {
    let mut offset = 0;
    let mut scissors = None;
    let mut run_start = None;
    let mut blank_start = None;
    for line in raw.split_inclusive('\n') {
        let content = line.trim_end_matches(['\n', '\r']);
        if scissors.is_none() && content == SCISSORS {
            scissors = Some(offset);
        }
        if content.trim().is_empty() {
            blank_start.get_or_insert(offset);
        } else if content.starts_with('#') {
            run_start.get_or_insert(blank_start.unwrap_or(offset));
            blank_start = None;
        } else {
            run_start = None;
            blank_start = None;
        }
        offset += line.len();
    }
    if let Some(at) = scissors {
        return raw.split_at(at);
    }
    match run_start {
        Some(at) if !raw[at..].lines().any(|l| classify(l, false).is_some()) => raw.split_at(at),
        _ => (raw, ""),
    }
}

/// The shape of attribution a trailer line carries, as if it sat in the final
/// trailer block. For the value of a `--trailer` option.
pub fn trailer_shape(line: &str) -> Option<Shape> {
    classify(line, true)
}

/// Whether a git author or committer name and email identify an AI tool. The
/// name must be the tool's own name, not a person who shares it, and the email
/// a vendor address or a bot handle.
pub fn is_ai_identity(name: &str, email: &str) -> bool {
    let name = name.trim().to_lowercase();
    let email = email.trim().to_lowercase();
    let vendor = AI_EMAIL_DOMAINS
        .iter()
        .any(|d| email.ends_with(&format!("@{d}")) || email.ends_with(&format!(".{d}")));
    let bot = email.contains("[bot]") && names_ai(&email);
    vendor || bot || AI_IDENTITY_NAMES.contains(&name.as_str()) || names_devin(&name)
}

fn classify(line: &str, in_trailer_block: bool) -> Option<Shape> {
    let trimmed = line.trim();
    let lower = trimmed.to_lowercase();
    let loose = trailer(trimmed);
    if loose.is_some_and(|(token, _)| token.eq_ignore_ascii_case("claude-session")) {
        Some(Shape::SessionTrailer)
    } else if is_claude_link(&lower) {
        Some(Shape::ClaudeLink)
    } else if has_session_id(&lower) {
        Some(Shape::SessionId)
    } else if is_footer(&lower) && names_ai(&lower) {
        Some(Shape::Footer)
    } else if loose.is_some_and(|(token, value)| is_credit_token(token) && credits_ai(token, value))
    {
        Some(Shape::CreditTrailer)
    } else if in_trailer_block
        && strict_trailer(line).is_some_and(|(token, value)| {
            names_ai(&token.to_lowercase()) || credits_ai(token, value)
        })
    {
        Some(Shape::AiTrailer)
    } else if line.contains('\u{1F916}') {
        Some(Shape::RobotEmoji)
    } else {
        None
    }
}

fn is_claude_link(lower: &str) -> bool {
    lower.contains("claude.ai/") || lower.contains("://claude.ai") || lower.contains("@claude.ai")
}

/// A `session_` followed by a long alphanumeric run with a digit in it, the
/// shape of an agent session id. Plain identifiers such as `session_cache`
/// have no digits and are short.
fn has_session_id(lower: &str) -> bool {
    lower.match_indices("session_").any(|(at, marker)| {
        let id: String = lower[at + marker.len()..]
            .chars()
            .take_while(char::is_ascii_alphanumeric)
            .collect();
        id.len() >= SESSION_ID_MIN_LEN && id.chars().any(|c| c.is_ascii_digit())
    })
}

/// A line that opens with a footer phrase once emoji, quote marks and
/// markdown decoration are skipped.
fn is_footer(lower: &str) -> bool {
    let body = lower.trim_start_matches(|c: char| !c.is_alphanumeric());
    FOOTER_PHRASES.iter().any(|phrase| body.starts_with(phrase))
}

/// A `Xxx-by` or `Xxx-with` trailer credits someone for the change.
fn is_credit_token(token: &str) -> bool {
    let token = token.to_lowercase();
    token.ends_with("-by") || token.ends_with("-with")
}

/// Whether a trailer value is an AI product or a vendor address: the display
/// name must be the product's own name, so `Claude Dupont` is a person. A
/// `Signed-off-by` is a person's certification, so for it only an address counts.
fn credits_ai(token: &str, value: &str) -> bool {
    let (name, address) = name_and_address(value);
    if token.eq_ignore_ascii_case("signed-off-by") {
        return is_vendor_address(address);
    }
    is_product_name(name) || is_vendor_address(address)
}

/// Splits `Name <address>`. A value with no brackets is an address when it has
/// an `@` and no blanks, and a name otherwise.
fn name_and_address(value: &str) -> (&str, &str) {
    let value = value.trim();
    if let Some((name, rest)) = value.rsplit_once('<') {
        if let Some(address) = rest.strip_suffix('>') {
            return (name, address);
        }
    }
    if value.contains('@') && !value.contains(char::is_whitespace) {
        ("", value)
    } else {
        (value, "")
    }
}

/// Whether `name` is an AI product's own name, optionally led by its vendor
/// and followed by a model, version or role, and nothing else.
fn is_product_name(name: &str) -> bool {
    let mut depth = 0;
    let outside: String = name
        .to_lowercase()
        .chars()
        .map(|c| match c {
            '(' => {
                depth += 1;
                ' '
            }
            ')' => {
                depth -= 1;
                ' '
            }
            _ if depth > 0 => ' ',
            _ => c,
        })
        .collect();
    let mut words: Vec<&str> = outside
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .collect();
    if words.len() > 1 && matches!(words[0], "github" | "google") {
        words.remove(0);
    }
    let known = |word: &&str| {
        PRODUCT_WORDS.contains(word)
            || NAME_QUALIFIERS.contains(word)
            || word.chars().any(|c| c.is_ascii_digit())
    };
    match words.split_first() {
        Some((&"devin", rest)) => rest.first() == Some(&"ai") && rest.iter().all(known),
        Some((first, rest)) => PRODUCT_WORDS.contains(first) && rest.iter().all(known),
        None => false,
    }
}

/// Whether `address` is a vendor's no-reply address or any bot's GitHub
/// no-reply address. A person's mailbox at a vendor is not.
fn is_vendor_address(address: &str) -> bool {
    let address = address.trim().to_lowercase();
    let Some((local, domain)) = address.rsplit_once('@') else {
        return false;
    };
    if domain == "users.noreply.github.com" {
        return local.ends_with("[bot]");
    }
    VENDOR_LOCAL_PARTS.contains(&local)
        && AI_EMAIL_DOMAINS
            .iter()
            .any(|d| domain == *d || domain.ends_with(&format!(".{d}")))
}

fn names_ai(lower: &str) -> bool {
    names_devin(lower)
        || AI_NAMES.iter().any(|name| {
            lower.match_indices(name).any(|(at, _)| {
                let before = lower[..at].chars().next_back();
                let after = lower[at + name.len()..].chars().next();
                let left_ok = !before.is_some_and(char::is_alphanumeric);
                let right_ok = name.ends_with('-') || !after.is_some_and(char::is_alphanumeric);
                left_ok && right_ok
            })
        })
}

/// Devin by its vendor address or by a bot handle, never by the first name.
fn names_devin(lower: &str) -> bool {
    lower.contains("devin.ai")
        || lower.contains("@cognition.ai")
        || lower
            .split(|c: char| c.is_whitespace() || "<>(),".contains(c))
            .any(|word| word.contains("devin") && word.contains("[bot]"))
}

/// Where git puts the separator of a trailer line: `Token`, optional blanks,
/// then `:`. The token holds only ASCII letters, digits and hyphens, so
/// `Co-Authored-By:Claude` and `Co-Authored-By : Claude` both qualify.
fn find_separator(line: &str) -> Option<usize> {
    let mut blank_seen = false;
    for (at, c) in line.char_indices() {
        if c == ':' {
            return (at > 0).then_some(at);
        }
        if !blank_seen && (c.is_ascii_alphanumeric() || c == '-') {
            continue;
        }
        if at > 0 && (c == ' ' || c == '\t') {
            blank_seen = true;
            continue;
        }
        return None;
    }
    None
}

/// The token and value of a trailer line, indented or not.
fn trailer(line: &str) -> Option<(&str, &str)> {
    let line = line.trim_start();
    let at = find_separator(line)?;
    Some((line[..at].trim_end(), line[at + 1..].trim()))
}

/// Like [`trailer`], but an indented line is a continuation, not a trailer.
fn strict_trailer(line: &str) -> Option<(&str, &str)> {
    if line.starts_with(char::is_whitespace) {
        None
    } else {
        trailer(line)
    }
}

/// The lines of the final trailer block, found the way `git
/// interpret-trailers` finds it: the last paragraph after the header, when
/// every line is a trailer or a continuation, or when a line git writes
/// itself is present and at least a quarter of the lines are trailers.
/// Comment lines are ignored.
fn trailer_block(lines: &[&str]) -> Option<Range<usize>> {
    let title_end = lines
        .iter()
        .position(|l| !l.starts_with('#') && l.trim().is_empty())?;
    let (mut trailers, mut prose, mut continuations) = (0, 0, 0);
    let (mut recognised, mut only_blank) = (false, true);
    for at in (title_end..lines.len()).rev() {
        let line = lines[at];
        if line.starts_with('#') {
            prose += continuations;
            continuations = 0;
        } else if line.trim().is_empty() {
            if only_blank {
                continue;
            }
            prose += continuations;
            let is_block = (recognised && trailers * 3 >= prose) || (trailers > 0 && prose == 0);
            return is_block.then(|| at + 1..lines.len());
        } else {
            only_blank = false;
            if GIT_GENERATED_PREFIXES.iter().any(|p| line.starts_with(p)) {
                trailers += 1;
                continuations = 0;
                recognised = true;
            } else if line.starts_with(char::is_whitespace) {
                continuations += 1;
            } else if find_separator(line).is_some() {
                trailers += 1;
                continuations = 0;
            } else {
                prose += 1 + continuations;
                continuations = 0;
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shapes(text: &str) -> Vec<(usize, Shape)> {
        sanitize(text).removed
    }

    fn only_shape(line: &str) -> Option<Shape> {
        classify(line, false)
    }

    #[test]
    fn each_attribution_shape_is_classified() {
        let table = [
            (
                "Claude-Session: https://claude.ai/code/session_01AbCdEfGhIjKlMnOpQrStUv",
                Shape::SessionTrailer,
            ),
            ("  claude-session: x", Shape::SessionTrailer),
            ("Claude-Session:x", Shape::SessionTrailer),
            ("Claude-Session : x", Shape::SessionTrailer),
            (
                "see https://claude.ai/code/session_1 for context",
                Shape::ClaudeLink,
            ),
            ("link: http://claude.ai", Shape::ClaudeLink),
            ("https://www.claude.ai/chat/abc", Shape::ClaudeLink),
            ("session_01NijQN9fPw6M94mYpVqMC8J", Shape::SessionId),
            (
                "Co-Authored-By: Claude <noreply@anthropic.com>",
                Shape::CreditTrailer,
            ),
            ("Co-Authored-By:Claude <a@b.c>", Shape::CreditTrailer),
            ("Co-Authored-By : Claude", Shape::CreditTrailer),
            ("Co-Authored-By  :Claude", Shape::CreditTrailer),
            ("co-authored-by: Anthropic", Shape::CreditTrailer),
            (
                "Co-authored-by: GitHub Copilot <c@github.com>",
                Shape::CreditTrailer,
            ),
            (
                "Co-authored-by: ChatGPT <x@openai.com>",
                Shape::CreditTrailer,
            ),
            ("Co-authored-by: gpt-4o", Shape::CreditTrailer),
            (
                "Co-authored-by: Gemini <g@google.com>",
                Shape::CreditTrailer,
            ),
            (
                "Co-authored-by: Cursor Agent <c@cursor.com>",
                Shape::CreditTrailer,
            ),
            ("Co-authored-by: Codeium", Shape::CreditTrailer),
            ("Co-authored-by: Windsurf", Shape::CreditTrailer),
            (
                "Co-authored-by: Devin AI <devin-ai-integration[bot]@users.noreply.github.com>",
                Shape::CreditTrailer,
            ),
            ("Co-authored-by: aider (gpt-4)", Shape::CreditTrailer),
            (
                "Co-authored-by: Codex <codex@openai.com>",
                Shape::CreditTrailer,
            ),
            (
                "Signed-off-by: Claude <noreply@anthropic.com>",
                Shape::CreditTrailer,
            ),
            ("Reviewed-by: Copilot", Shape::CreditTrailer),
            ("Generated-with: Claude Code", Shape::CreditTrailer),
            ("Generated with Claude Code", Shape::Footer),
            ("# Generated with Claude Code", Shape::Footer),
            (
                "Generated with [Claude Code](https://claude.com/claude-code)",
                Shape::Footer,
            ),
            ("generated with Cursor", Shape::Footer),
            ("Generated by GitHub Copilot", Shape::Footer),
            ("Created with Windsurf", Shape::Footer),
            (
                "\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)",
                Shape::Footer,
            ),
            ("> Written by ChatGPT", Shape::Footer),
            ("\u{1F916} anything", Shape::RobotEmoji),
        ];
        for (line, expected) in table {
            assert_eq!(only_shape(line), Some(expected), "line: {line}");
        }
    }

    #[test]
    fn legitimate_lines_are_untouched() {
        let clean = [
            "feat(hooks): add the commit message sanitiser",
            "Refs: PLAT-123",
            "Fixes: #12",
            "Reviewed-by: Sam Lee <sam@example.com>",
            "Signed-off-by: Sam Lee <sam@example.com>",
            "Co-authored-by: Sam Lee <sam@example.com>",
            "Co-authored-by: Devin Smith <devin@example.com>",
            "Document the Claude Code plugin install steps",
            "The Claude Code plugin now ships the sanitiser.",
            "Bump the anthropic SDK from 0.1 to 0.2",
            "Refs: https://github.com/anthropics/claude-code/issues/1",
            "Switch the cursor position handling to the grid",
            "Fix the gemini feed parser for the copilot team",
            "Output generated by the build script",
            "This was generated with cargo run",
            "Session cache is cleared on exit",
            "see the session_cache and session_initialization docs",
            "devine intervention",
            "Ask Devin about it",
            "The Claude-Session: trailer is removed by the sanitiser",
            "- Claude-Session: lines are dropped",
            "",
        ];
        for line in clean {
            assert_eq!(only_shape(line), None, "line: {line}");
        }
    }

    #[test]
    fn a_bot_handle_matches_devin_but_the_first_name_does_not() {
        assert!(names_ai("devin-ai-integration[bot]"));
        assert!(names_ai("<noreply@devin.ai>"));
        assert!(!names_ai("devin"));
        assert!(!names_ai("devin smith <devin@example.com>"));
    }

    #[test]
    fn removed_lines_are_reported_by_number_and_shape_only() {
        let text =
            "feat: x\n\nbody\nClaude-Session: secret-value\nfine\nGenerated with Claude Code";

        let got = sanitize(text);

        assert_eq!(
            got.removed,
            vec![(4, Shape::SessionTrailer), (6, Shape::Footer)]
        );
        assert_eq!(got.text, "feat: x\n\nbody\nfine");
        let rendered = format!("{:?} {:?}", got.removed, got.problems());
        assert!(!rendered.contains("secret-value"), "{rendered}");
    }

    #[test]
    fn a_clean_message_is_returned_unchanged() {
        let text = "feat: x\r\n\r\nbody\r\n\r\nRefs: 1\r\n";

        assert_eq!(
            sanitize(text),
            Sanitized {
                text: text.to_string(),
                removed: Vec::new()
            }
        );
    }

    #[test]
    fn removing_a_trailer_does_not_leave_stray_blank_lines() {
        let table = [
            (
                "feat: x\n\nbody\n\nCo-authored-by: Claude\n",
                "feat: x\n\nbody\n",
            ),
            (
                "feat: x\n\nbody\n\nCo-authored-by: Claude\n\nRefs: 1\n",
                "feat: x\n\nbody\n\nRefs: 1\n",
            ),
            (
                "feat: x\n\nbody\n\nRefs: 1\nCo-authored-by: Claude\nSigned-off-by: A <a@b.c>\n",
                "feat: x\n\nbody\n\nRefs: 1\nSigned-off-by: A <a@b.c>\n",
            ),
            (
                "feat: x\n\nbody\n\nGenerated with Claude Code",
                "feat: x\n\nbody",
            ),
            (
                "\u{1F916} Generated with Claude Code\n\nfeat: x\n",
                "feat: x\n",
            ),
        ];
        for (input, expected) in table {
            assert_eq!(sanitize(input).text, expected, "input: {input:?}");
        }
    }

    #[test]
    fn a_blank_run_that_was_already_there_is_kept() {
        let text = "feat: x\n\n\nbody\nClaude-Session: u\n";

        assert_eq!(sanitize(text).text, "feat: x\n\n\nbody\n");
    }

    #[test]
    fn comment_lines_inside_a_message_are_kept_and_still_sanitised() {
        let text = "feat: x\n\n# a note for the reader\nbody\n# Generated with Claude Code\nmore\n";

        let got = sanitize(text);

        assert_eq!(got.removed, vec![(5, Shape::Footer)]);
        assert_eq!(got.text, "feat: x\n\n# a note for the reader\nbody\nmore\n");
    }

    #[test]
    fn an_editor_template_is_kept_byte_for_byte() {
        let template =
            "\n# Please enter the commit message for your changes.\n#\n# On branch claude/fix\n";
        let raw = format!("feat: x\n\nbody\nClaude-Session: u\n{template}");

        let got = sanitize_editor(&raw);

        assert_eq!(got.removed, vec![(4, Shape::SessionTrailer)]);
        assert_eq!(got.text, format!("feat: x\n\nbody\n{template}"));
    }

    #[test]
    fn everything_below_the_scissors_line_is_never_inspected() {
        let raw = format!("feat: x\n\nRefs: 1\n{SCISSORS}\n+Claude-Session: in a diff\n");

        let got = sanitize_editor(&raw);

        assert_eq!(got.removed, Vec::new());
        assert_eq!(got.text, raw);
    }

    #[test]
    fn a_trailing_comment_block_with_attribution_is_not_a_template() {
        let raw = "feat: x\n\nbody\n\n# Generated with Claude Code\n";

        let got = sanitize_editor(raw);

        assert_eq!(got.removed, vec![(5, Shape::Footer)]);
        assert_eq!(got.text, "feat: x\n\nbody\n");
    }

    #[test]
    fn a_trailer_in_the_final_block_that_names_an_ai_is_removed_by_its_token() {
        let text = "feat: x\n\nbody\n\nRefs: 1\nClaude-Model: opus\nCopilot-Review: ok\n";

        assert_eq!(
            shapes(text),
            vec![(6, Shape::AiTrailer), (7, Shape::AiTrailer)]
        );
    }

    #[test]
    fn a_trailer_outside_the_final_block_is_judged_as_a_line_only() {
        let text = "feat: x\n\nClaude-Model: opus\n\nprose closing paragraph\n";

        assert_eq!(shapes(text), Vec::new());
    }

    #[test]
    fn prose_has_no_trailer_block() {
        let text = "## Summary\n\nbody\n\nClaude-Model: opus\nCo-authored-by:Claude";

        let got = sanitize_prose(text);

        assert_eq!(got.removed, vec![(6, Shape::CreditTrailer)]);
    }

    #[test]
    fn other_human_trailers_are_kept() {
        let text = "feat: x\n\nbody\n\nFixes: #1\nReviewed-by: Sam <s@x.y>\nChange-Id: I1\n";

        assert_eq!(sanitize(text).text, text);
    }

    #[test]
    fn a_header_shaped_like_a_trailer_is_not_a_trailer_block() {
        assert_eq!(shapes("Claude-Model: opus"), Vec::new());
        assert_eq!(shapes("fix: thing\nClaude-Model: opus"), Vec::new());
    }

    #[test]
    fn problems_are_one_sentence_per_removed_line() {
        let got = sanitize("feat: x\n\nGenerated with Claude Code\n").problems();

        assert_eq!(
            got,
            vec!["line 3 carries AI attribution (generated-with footer)".to_string()]
        );
    }

    #[test]
    fn a_co_author_who_is_a_person_passes_the_commit_message_path() {
        let message = "feat: x\n\nbody\n\nCo-authored-by: Sam Lee <sam@example.com>\n";

        assert_eq!(problems(message), Vec::new());
        assert_eq!(
            problems("feat: x\n\nbody\n\nCo-authored-by: Claude <noreply@anthropic.com>\n"),
            vec![(5, Shape::CreditTrailer)]
        );
    }

    /// The trailers `git interpret-trailers --parse` finds in `message`.
    fn git_trailers(message: &str) -> Vec<String> {
        use std::io::Write;
        use std::process::{Command, Stdio};
        let mut child = Command::new("git")
            .args(["interpret-trailers", "--parse"])
            .env("GIT_CONFIG_GLOBAL", "/dev/null")
            .env("GIT_CONFIG_NOSYSTEM", "1")
            // Another test may have changed this process's directory and removed it.
            .current_dir(std::env::temp_dir())
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .expect("git spawns");
        child
            .stdin
            .take()
            .expect("stdin")
            .write_all(message.as_bytes())
            .expect("message written");
        let out = child.wait_with_output().expect("git exits");
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .map(|l| l.trim_end().to_string())
            .collect()
    }

    /// The trailers [`trailer_block`] finds, in git's normalised `Token: value`.
    fn our_trailers(message: &str) -> Vec<String> {
        let lines: Vec<&str> = message.lines().collect();
        let Some(block) = trailer_block(&lines) else {
            return Vec::new();
        };
        let mut trailers: Vec<String> = Vec::new();
        for line in lines[block].iter().filter(|l| !l.starts_with('#')) {
            if let Some((token, value)) = strict_trailer(line) {
                trailers.push(format!("{token}: {value}").trim_end().to_string());
            } else if let Some(last) = trailers
                .last_mut()
                .filter(|_| line.starts_with(char::is_whitespace))
            {
                last.push(' ');
                last.push_str(line.trim());
            }
        }
        trailers
    }

    #[test]
    fn a_credit_is_ai_attribution_by_its_display_name_or_a_vendor_address() {
        let ai = [
            "Co-authored-by: Claude",
            "Co-authored-by: Claude Code <x@example.com>",
            "Co-authored-by: Claude Opus 4.5 <noreply@anthropic.com>",
            "Co-authored-by: Claude Sonnet 4",
            "Co-authored-by: Claude 3.5 Sonnet",
            "Co-authored-by: Claude Haiku",
            "Co-authored-by: Anthropic",
            "Co-authored-by: ChatGPT",
            "Co-authored-by: OpenAI Codex",
            "Co-authored-by: GitHub Copilot <c@github.com>",
            "Co-authored-by: Copilot",
            "Co-authored-by: Gemini",
            "Co-authored-by: Gemini 2.5 Pro",
            "Co-authored-by: Gemini Flash <g@google.com>",
            "Co-authored-by: GPT-4 Turbo",
            "Co-authored-by: Claude Sonnet 4 Thinking",
            "Generated-by: Claude Code (https://claude.com/claude-code)",
            "Co-authored-by: Cursor Agent",
            "Co-authored-by: aider (gpt-4)",
            "Co-authored-by: Devin AI",
            "Signed-off-by: Jane Doe <noreply@anthropic.com>",
            "Signed-off-by: Jane Doe <no-reply@openai.com>",
            "Co-authored-by: Jane Doe <cursoragent@cursor.com>",
            "Co-authored-by: Jane Doe <devin-ai-integration[bot]@users.noreply.github.com>",
            "Co-authored-by: Bot <49699333+dependabot[bot]@users.noreply.github.com>",
            "Reviewed-by: noreply@anthropic.com",
        ];
        let kept = [
            "Co-authored-by: Claude Dupont <claude@example.fr>",
            "Co-authored-by: Jane Doe <jane@anthropic.com>",
            "Signed-off-by: Jane Doe <jane@anthropic.com>",
            "Signed-off-by: Claude Dupont <claude.dupont@example.com>",
            "Signed-off-by: Jane Doe <jane@users.noreply.github.com>",
            "Co-authored-by: Gemini Rodriguez <g@example.com>",
            "Co-authored-by: Devin Smith <devin@example.com>",
            "Co-authored-by: Devin <devin@example.com>",
            "Co-authored-by: Jane Doe <jane@cursor.com>",
            "Signed-off-by: Claude <claude@example.fr>",
            "Signed-off-by: Claude",
            "Signed-off-by: Gemini Pro <g@example.com>",
            "Reported-with: https://github.com/anthropics/claude-code/issues/1",
        ];
        for line in ai {
            assert_eq!(only_shape(line), Some(Shape::CreditTrailer), "{line}");
        }
        for line in kept {
            assert_eq!(only_shape(line), None, "{line}");
        }
    }

    #[test]
    fn a_sign_off_is_an_ais_only_through_a_vendor_address_even_in_the_final_block() {
        let message = "feat: x\n\nbody\n\nSigned-off-by: Claude <claude@example.fr>\nSigned-off-by: Gemini Pro\nSigned-off-by: Claude <noreply@anthropic.com>\n";

        let got = sanitize(message);

        assert_eq!(got.removed, vec![(7, Shape::CreditTrailer)]);
        assert_eq!(
            got.text,
            "feat: x\n\nbody\n\nSigned-off-by: Claude <claude@example.fr>\nSigned-off-by: Gemini Pro\n"
        );
    }

    #[test]
    fn has_sign_off_looks_for_the_trailer_at_the_start_of_a_line() {
        assert!(has_sign_off("feat: x\n\nSigned-off-by: A <a@b.c>\n"));
        assert!(!has_sign_off(
            "feat: x\n\nbody mentions Signed-off-by: here\n"
        ));
        assert!(!has_sign_off("feat: x\n"));
    }

    #[test]
    fn a_human_sign_off_survives_so_the_dco_check_still_passes() {
        let message = "feat: x\n\nbody\n\nCo-authored-by: Claude <noreply@anthropic.com>\nSigned-off-by: Claude Dupont <claude@example.fr>\nSigned-off-by: Jane Doe <jane@anthropic.com>\n";

        let got = sanitize(message);

        assert_eq!(got.removed, vec![(5, Shape::CreditTrailer)]);
        assert!(
            got.text.contains("Signed-off-by:"),
            "the DCO check looks for this text: {}",
            got.text
        );
        assert_eq!(
            got.text,
            "feat: x\n\nbody\n\nSigned-off-by: Claude Dupont <claude@example.fr>\nSigned-off-by: Jane Doe <jane@anthropic.com>\n"
        );
    }

    #[test]
    fn a_trailer_value_that_is_an_ai_product_is_removed_from_the_final_block() {
        let text = "feat: x\n\nbody\n\nRefs: 1\nAssistant: Claude Opus 4.5\nAI-Tool: GitHub Copilot\nSee-Also: https://github.com/anthropics/claude-code/issues/1\nReported-by: Claude Dupont\nNote: the claude code plugin\n";

        let got = sanitize(text);

        assert_eq!(
            got.removed,
            vec![(6, Shape::AiTrailer), (7, Shape::AiTrailer)]
        );
        assert_eq!(
            got.text,
            "feat: x\n\nbody\n\nRefs: 1\nSee-Also: https://github.com/anthropics/claude-code/issues/1\nReported-by: Claude Dupont\nNote: the claude code plugin\n"
        );
    }

    #[test]
    fn a_trailer_value_outside_the_final_block_is_left_alone() {
        let text = "feat: x\n\nAssistant: Claude Opus 4.5\n\nprose closing paragraph\n";

        assert_eq!(shapes(text), Vec::new());
    }

    #[test]
    fn a_folded_trailer_is_removed_whole_and_the_rest_still_parses() {
        let credit = Shape::CreditTrailer;
        let messages = [
            (
                "feat: x\n\nbody\n\nRefs: 1\nCo-authored-by: Claude\n <noreply@anthropic.com>\nSigned-off-by: Sam <s@x.y>\n",
                vec![(6, credit), (7, credit)],
            ),
            (
                "feat: x\n\nbody\n\nRefs: 1\nCo-authored-by: Sam\n  Claude <noreply@anthropic.com>\nSigned-off-by: Sam <s@x.y>\n",
                vec![(6, credit), (7, credit)],
            ),
            (
                "feat: x\n\nbody\n\nRefs: 1\nAssistant:\n\tClaude Opus\n\t4.5\nSigned-off-by: Sam <s@x.y>\n",
                vec![
                    (6, Shape::AiTrailer),
                    (7, Shape::AiTrailer),
                    (8, Shape::AiTrailer),
                ],
            ),
        ];
        for (message, removed) in messages {
            let got = sanitize(message);

            assert_eq!(
                git_trailers(&got.text),
                vec![
                    "Refs: 1".to_string(),
                    "Signed-off-by: Sam <s@x.y>".to_string()
                ],
                "message: {message:?}"
            );
            assert!(git_trailers(message).len() == 3, "{message:?}");
            assert_eq!(
                got.text, "feat: x\n\nbody\n\nRefs: 1\nSigned-off-by: Sam <s@x.y>\n",
                "message: {message:?}"
            );
            assert_eq!(got.removed, removed, "message: {message:?}");
        }
    }

    #[test]
    fn a_continuation_inside_a_removed_unit_is_reported_once() {
        let message = "feat: x\n\nbody\n\nRefs: 1\nCo-authored-by: Claude\n  session_01AbCdEfGhIjKlMnOpQr\nSigned-off-by: Sam <s@x.y>\n";

        let got = sanitize(message);

        assert_eq!(
            got.removed,
            vec![(6, Shape::SessionId), (7, Shape::SessionId)]
        );
        assert_eq!(
            got.text,
            "feat: x\n\nbody\n\nRefs: 1\nSigned-off-by: Sam <s@x.y>\n"
        );
    }

    #[test]
    fn an_indented_line_outside_the_trailer_block_is_judged_by_itself() {
        let commit = "feat: x\n\nCo-authored-by: Claude\n  Opus 4.5\n\nclosing prose\n";
        let prose = "## Summary\n\nCo-authored-by: Claude\n  Opus 4.5\n";

        let in_commit = sanitize(commit);
        let in_prose = sanitize_prose(prose);

        assert_eq!(in_commit.removed, vec![(3, Shape::CreditTrailer)]);
        assert_eq!(in_commit.text, "feat: x\n\n  Opus 4.5\n\nclosing prose\n");
        assert_eq!(in_prose.removed, vec![(3, Shape::CreditTrailer)]);
        assert_eq!(in_prose.text, "## Summary\n\n  Opus 4.5\n");
    }

    #[test]
    fn a_folded_trailer_from_a_person_is_kept_whole() {
        let text =
            "feat: x\n\nbody\n\nRefs: 1\nCo-authored-by: Claude\n  Dupont <claude@example.fr>\n";

        assert_eq!(sanitize(text).text, text);
    }

    #[test]
    fn the_trailer_block_agrees_with_git_interpret_trailers() {
        let messages = [
            "feat: x\n\nbody\n\nCo-Authored-By:Claude <a@b.c>\n",
            "feat: x\n\nbody\n\nCo-Authored-By : Claude <a@b.c>\n",
            "feat: x\n\nbody\n\nCo-Authored-By  : Claude\n",
            "feat: x\n\nbody\n\nCo-Authored-By:\tClaude\n",
            "feat: x\n\nbody\n\nCo-Authored-By:   \n",
            "feat: x\n\nbody\n\nCo  -Authored-By: Claude\n",
            "feat: x\n\nbody\n\nCo Authored: Claude\n",
            "feat: x\n\nbody\n\nCo_Authored: Claude\n",
            "feat: x\n\nbody\n\n Co-Authored-By: Claude\n",
            "feat: x\nCo-Authored-By: Claude\n",
            "feat: x\n\nCo-Authored-By: Claude\n",
            "feat: x\n\nbody\nCo-Authored-By: Claude\n",
            "feat: x\n\nbody\n\nnot a trailer\nCo-Authored-By: Claude\n",
            "feat: x\n\nbody\n\nnot a trailer\nSigned-off-by: A <a@b.c>\nCo-Authored-By: Claude\n",
            "feat: x\n\nbody\n\nA: 1\nB: 2\nC: 3\nnot\nSigned-off-by: s\n",
            "feat: x\n\nbody\n\n1\n2\n3\nSigned-off-by: s\n",
            "feat: x\n\nbody\n\n1\n2\n3\n4\nSigned-off-by: s\n",
            "feat: x\n\nbody\n\nFixes: 1\nnot a trailer\nsecond\nthird\nfourth\n",
            "feat: x\n\nbody\n\nFixes: 1\n# comment\nCo-Authored-By: Claude\n",
            "feat: x\n\nbody\n\nFixes: 1\nCo-Authored-By: Claude\n# comment\n",
            "feat: x\n\nbody\n\nFixes: 1\nCo-Authored-By: Claude\n\n# Please enter\n# more\n",
            "feat: x\n\nbody\n\nFixes: 1\nCo-Authored-By:Claude\nCo-Authored-By :Claude\n",
            "feat: x\n\nbody\n\nRefs: 1\nCo-Authored-By: Claude\n <noreply@anthropic.com>\nFixes: 2\n",
            "feat: x\n\nbody\n\nAssistant:\n\tClaude Opus\n\t4.5\n",
            "feat: x\n\nbody\n\n(cherry picked from commit abc)\nnot a trailer\n",
            "feat: x\n\nbody\n\nGenerated with [Claude Code](https://claude.com)\n",
            "Signed-off-by: a\n",
            "feat: x\n\nSigned-off-by: a\n\n",
            "feat: x\n\n\n\nbody\n\n\nFixes: 1\n\n\n",
        ];
        assert_eq!(
            git_trailers("feat: x\n\nRefs: 1\n"),
            vec!["Refs: 1".to_string()],
            "git is available and reports trailers"
        );
        for message in messages {
            assert_eq!(
                our_trailers(message),
                git_trailers(message),
                "message: {message:?}"
            );
        }
    }

    #[test]
    fn an_identity_is_an_ai_by_vendor_address_or_exact_tool_name() {
        let table = [
            ("Claude", "noreply@anthropic.com", true),
            ("Claude Code", "x@example.com", true),
            ("Anyone", "bot@mail.anthropic.com", true),
            (
                "copilot-swe-agent[bot]",
                "198982749+copilot[bot]@users.noreply.github.com",
                true,
            ),
            (
                "Devin AI",
                "devin-ai-integration[bot]@users.noreply.github.com",
                true,
            ),
            ("Claude Dupont", "claude@example.fr", false),
            ("Devin Smith", "devin@example.com", false),
            ("Sam Lee", "sam@example.com", false),
        ];
        for (name, email, expected) in table {
            assert_eq!(is_ai_identity(name, email), expected, "{name} <{email}>");
        }
    }

    #[test]
    fn a_trailer_value_is_judged_as_part_of_the_final_block() {
        assert_eq!(
            trailer_shape("Co-authored-by: Claude <noreply@anthropic.com>"),
            Some(Shape::CreditTrailer)
        );
        assert_eq!(trailer_shape("Claude-Model: opus"), Some(Shape::AiTrailer));
        assert_eq!(trailer_shape("Refs: PLAT-1"), None);
    }

    #[test]
    fn drop_lines_removes_exactly_the_named_lines() {
        let text = "feat: x\n\nbody\nmid\nRefs: 1\n";

        let got = drop_lines(text, &[(4, Shape::Footer)]);

        assert_eq!(got, "feat: x\n\nbody\nRefs: 1\n");
        assert_eq!(drop_lines(text, &[]), text);
    }
}
