// SPDX-FileCopyrightText: 2026 Igor Santos
// SPDX-License-Identifier: MIT

//! The one definition of a pristine commit message, shared by the PR guard,
//! the `commit-message-guard` hook and `playbook check commit-msg`.
//!
//! A message is a conventional header, an optional body and trailers. Only
//! `Refs`, `Signed-off-by` and `Co-authored-by` may be trailers, and none of
//! them may name an AI.
//!
//! The line check blocks the attribution SHAPES, not every mention of a
//! product name: prose such as "the Claude Code plugin" is allowed, while a
//! `Claude-Session:` line, a claude.ai link, a session id, a "Generated with"
//! footer or a `*-by`/`*-with` trailer that names an AI is not.

/// Trailer tokens a commit message may carry, lowercase.
pub const ALLOWED_TRAILERS: [&str; 3] = ["refs", "signed-off-by", "co-authored-by"];

/// Names of AI tools and vendors, lowercase. A name matches as a whole word,
/// except `gpt-`, which is a prefix of model names such as `gpt-4o`.
const AI_NAMES: [&str; 13] = [
    "claude",
    "anthropic",
    "openai",
    "chatgpt",
    "gpt-",
    "copilot",
    "gemini",
    "cursor",
    "codeium",
    "windsurf",
    "devin",
    "aider",
    "codex",
];

/// Openers of a tool footer such as "Generated with Claude Code".
const FOOTER_PHRASES: [&str; 9] = [
    "generated with",
    "generated by",
    "created with",
    "created by",
    "made with",
    "written by",
    "assisted by",
    "authored by",
    "built with",
];

const SESSION_ID_MIN_LEN: usize = 16;

/// Whether one line carries AI attribution.
pub fn attribution_hit(line: &str) -> bool {
    let lower = line.to_lowercase();
    lower.contains("claude-session:")
        || is_claude_link(&lower)
        || has_session_id(&lower)
        || (is_footer(&lower) && names_ai(&lower))
        || (trailer(line).is_some_and(|(token, _)| is_credit_token(token)) && names_ai(&lower))
        || line.contains('\u{1F916}')
}

fn is_claude_link(lower: &str) -> bool {
    lower.contains("claude.ai/") || lower.contains("://claude.ai") || lower.contains("@claude.ai")
}

/// A `session_` followed by a long alphanumeric run with a digit in it, the
/// shape of an agent session id. Plain identifiers such as `session_cache`
/// have no digits and are short.
fn has_session_id(lower: &str) -> bool {
    lower.match_indices("session_").any(|(at, marker)| {
        let id: String = lower[at + marker.len()..]
            .chars()
            .take_while(char::is_ascii_alphanumeric)
            .collect();
        id.len() >= SESSION_ID_MIN_LEN && id.chars().any(|c| c.is_ascii_digit())
    })
}

/// A line that opens with a footer phrase once emoji, quote marks and
/// markdown decoration are skipped.
fn is_footer(lower: &str) -> bool {
    let body = lower.trim_start_matches(|c: char| !c.is_alphanumeric());
    FOOTER_PHRASES.iter().any(|phrase| body.starts_with(phrase))
}

/// A `Xxx-by` or `Xxx-with` trailer credits someone for the change.
fn is_credit_token(token: &str) -> bool {
    let token = token.to_lowercase();
    token.ends_with("-by") || token.ends_with("-with")
}

fn names_ai(lower: &str) -> bool {
    AI_NAMES.iter().any(|name| {
        lower.match_indices(name).any(|(at, _)| {
            let before = lower[..at].chars().next_back();
            let after = lower[at + name.len()..].chars().next();
            let left_ok = !before.is_some_and(char::is_alphanumeric);
            let right_ok = name.ends_with('-') || !after.is_some_and(char::is_alphanumeric);
            left_ok && right_ok
        })
    })
}

/// The token and value of a trailer line: an ASCII token of letters, digits
/// and hyphens, a colon, whitespace, then a value.
fn trailer(line: &str) -> Option<(&str, &str)> {
    let (token, value) = line.trim_end().split_once(':')?;
    let token = token.trim_start();
    let is_token =
        !token.is_empty() && token.chars().all(|c| c.is_ascii_alphanumeric() || c == '-');
    let spaced = value.starts_with(char::is_whitespace) && !value.trim().is_empty();
    (is_token && spaced).then_some((token, value.trim()))
}

/// Every line of `text` that carries AI attribution, as `(line number from 1,
/// the line)`.
pub fn attribution_lines(text: &str) -> Vec<(usize, String)> {
    text.lines()
        .enumerate()
        .filter(|(_, line)| attribution_hit(line))
        .map(|(i, line)| (i + 1, line.trim().to_string()))
        .collect()
}

/// Trailers in the message's last paragraph whose token is not allowed, as
/// `(line number from 1, token)`. Applies only when that paragraph is made
/// solely of `Token: value` lines and is not the header paragraph.
pub fn disallowed_trailers(message: &str) -> Vec<(usize, String)> {
    let lines: Vec<&str> = message.lines().collect();
    let is_blank = |line: &&str| line.trim().is_empty();
    let Some(last) = lines.iter().rposition(|line| !is_blank(line)) else {
        return Vec::new();
    };
    let first = lines.iter().position(|line| !is_blank(line)).unwrap_or(0);
    let start = lines[..last]
        .iter()
        .rposition(is_blank)
        .map_or(0, |blank| blank + 1);
    if start <= first {
        return Vec::new();
    }
    let paragraph = &lines[start..=last];
    let folded = |line: &str| line.starts_with([' ', '\t']);
    let all_trailers = paragraph
        .iter()
        .enumerate()
        .all(|(i, line)| trailer(line).is_some() || (i > 0 && folded(line)));
    if !all_trailers {
        return Vec::new();
    }
    paragraph
        .iter()
        .enumerate()
        .filter_map(|(i, line)| trailer(line).map(|(token, _)| (start + i + 1, token)))
        .filter(|(_, token)| !ALLOWED_TRAILERS.contains(&token.to_lowercase().as_str()))
        .map(|(n, token)| (n, token.to_string()))
        .collect()
}

/// Every problem in a commit-style message, one plain sentence each.
pub fn commit_message_problems(message: &str) -> Vec<String> {
    let mut out = prose_problems(message);
    out.extend(trailer_problems(message));
    out
}

/// One plain sentence per trailer from [`disallowed_trailers`]. It names the
/// token, never the value, which may be a person's address.
pub fn trailer_problems(message: &str) -> Vec<String> {
    disallowed_trailers(message)
        .into_iter()
        .map(|(n, token)| {
            format!(
                "line {n} has the trailer \"{token}\", only Refs, Signed-off-by and Co-authored-by are allowed"
            )
        })
        .collect()
}

/// Every problem in free text such as a PR title or body, where only the line
/// check applies.
pub fn prose_problems(text: &str) -> Vec<String> {
    attribution_lines(text)
        .into_iter()
        .map(|(n, line)| format!("line {n} (\"{line}\") carries AI attribution"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn attribution_lines_are_hits() {
        let hits = [
            "Claude-Session: https://claude.ai/code/session_01AbCdEfGhIjKlMnOpQrStUv",
            "  claude-session: x",
            "see https://claude.ai/code/session_1 for context",
            "link: http://claude.ai",
            "https://www.claude.ai/chat/abc",
            "session_01NijQN9fPw6M94mYpVqMC8J",
            "Co-Authored-By: Claude <noreply@anthropic.com>",
            "co-authored-by: Anthropic",
            "Co-authored-by: GitHub Copilot <copilot@github.com>",
            "Co-authored-by: ChatGPT <x@openai.com>",
            "Co-authored-by: gpt-4o",
            "Co-authored-by: Gemini <g@google.com>",
            "Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
            "Co-authored-by: Codeium",
            "Co-authored-by: Windsurf",
            "Co-authored-by: Devin AI <devin-ai-integration[bot]@users.noreply.github.com>",
            "Co-authored-by: aider (gpt-4)",
            "Co-authored-by: Codex <codex@openai.com>",
            "Signed-off-by: Claude <noreply@anthropic.com>",
            "Reviewed-by: Copilot",
            "Generated-with: Claude Code",
            "Generated with Claude Code",
            "Generated with [Claude Code](https://claude.com/claude-code)",
            "generated with Cursor",
            "Generated by GitHub Copilot",
            "Created with Windsurf",
            "\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)",
            "> Written by ChatGPT",
            "\u{1F916} anything",
        ];
        for line in hits {
            assert!(attribution_hit(line), "should be a hit: {line}");
        }
    }

    #[test]
    fn legitimate_lines_are_not_hits() {
        let clean = [
            "feat(hooks): add the commit message guard",
            "Refs: PLAT-123",
            "Signed-off-by: Sam Lee <sam@example.com>",
            "Co-authored-by: Sam Lee <sam@example.com>",
            "Document the Claude Code plugin install steps",
            "The Claude Code plugin now ships the guard.",
            "Bump the anthropic SDK from 0.1 to 0.2",
            "Switch the cursor position handling to the grid",
            "Fix the gemini feed parser for the copilot team",
            "Output generated by the build script",
            "This was generated with cargo run",
            "Session cache is cleared on exit",
            "see the session_cache and session_initialization docs",
            "Note: the Claude Code plugin is unchanged",
            "devine intervention",
            "",
        ];
        for line in clean {
            assert!(!attribution_hit(line), "should be clean: {line}");
        }
    }

    #[test]
    fn attribution_lines_report_their_number_and_text() {
        let text = "feat: x\n\nbody\nClaude-Session: u\nfine\nGenerated with Claude Code";

        let got = attribution_lines(text);

        assert_eq!(
            got,
            vec![
                (4, "Claude-Session: u".to_string()),
                (6, "Generated with Claude Code".to_string())
            ]
        );
    }

    #[test]
    fn trailers_outside_the_allowed_set_are_reported() {
        let table: [(&str, Vec<(usize, &str)>); 14] = [
            ("feat: x\n\nRefs: 1\nSigned-off-by: A <a@b.c>", vec![]),
            (
                "feat: x\n\nbody\n\nREFS: 1\nsigned-off-by: A\nCO-AUTHORED-BY: B",
                vec![],
            ),
            ("feat: x\n\nbody\n\nFixes: #1", vec![(5, "Fixes")]),
            ("feat: x\n\nChange-Id: I1\nRefs: 2", vec![(3, "Change-Id")]),
            (
                "feat: x\n\nReviewed-by: A\nTested-by: B",
                vec![(3, "Reviewed-by"), (4, "Tested-by")],
            ),
            (
                "feat: x\n\nBREAKING-CHANGE: gone",
                vec![(3, "BREAKING-CHANGE")],
            ),
            (
                "feat: x\n\nbody\n\nClaude-Session: u",
                vec![(5, "Claude-Session")],
            ),
            // The header is never a trailer, even when it is shaped like one.
            ("fix: thing", vec![]),
            ("fix: thing\n", vec![]),
            // A last paragraph with any non-trailer line is body prose.
            ("feat: x\n\nWhy: because\nand then some prose", vec![]),
            ("feat: x\n\nBREAKING CHANGE: gone", vec![]),
            // A trailer-shaped line that is not in the last paragraph is body.
            ("feat: x\n\nWhy: because\n\nplain closing paragraph", vec![]),
            // A body paragraph shaped like a trailer is treated as one, as git does.
            ("feat: x\n\nNote: see the docs", vec![(3, "Note")]),
            ("feat: x\n\nRefs: 1\n  continued\nSigned-off-by: A", vec![]),
        ];
        for (message, expected) in table {
            let want: Vec<(usize, String)> = expected
                .into_iter()
                .map(|(n, t)| (n, t.to_string()))
                .collect();
            assert_eq!(disallowed_trailers(message), want, "message: {message:?}");
        }
    }

    #[test]
    fn a_pristine_message_has_no_problems() {
        let message = "feat(hooks): block attribution\n\n- stops AI trailers\n- the Claude Code plugin is unchanged\n\nRefs: PLAT-1\nSigned-off-by: Sam Lee <sam@example.com>\nCo-authored-by: Kim Wu <kim@example.com>\n";

        assert_eq!(commit_message_problems(message), Vec::<String>::new());
    }

    #[test]
    fn commit_problems_name_the_line_and_never_echo_a_trailer_value() {
        let message = "feat: x\n\nbody\n\nFixes: jane@example.com\nClaude-Session: u";

        let got = commit_message_problems(message);

        assert_eq!(
            got,
            vec![
                "line 6 (\"Claude-Session: u\") carries AI attribution".to_string(),
                "line 5 has the trailer \"Fixes\", only Refs, Signed-off-by and Co-authored-by are allowed".to_string(),
                "line 6 has the trailer \"Claude-Session\", only Refs, Signed-off-by and Co-authored-by are allowed".to_string(),
            ]
        );
    }

    #[test]
    fn prose_checks_lines_but_never_trailers() {
        let text = "## Summary\n\nbody\n\nFixes: #1\nCo-authored-by: Claude";

        let got = prose_problems(text);

        assert_eq!(
            got,
            vec!["line 6 (\"Co-authored-by: Claude\") carries AI attribution".to_string()]
        );
        assert_eq!(prose_problems("Fixes: #1"), Vec::<String>::new());
    }
}
